# Generated by Django 5.2.6 on 2025-09-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
        ('violations', '0002_violationclassifier_violation_violation_classifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectorviolation',
            name='violation_classifier',
            field=models.ForeignKey(blank=True, help_text='Тип замечания из классификатора производства работ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspector_violations', to='violations.violationclassifier', verbose_name='Классификатор нарушения'),
        ),
    ]
