# Generated by Django 5.2.6 on 2025-09-28 23:39

from django.db import migrations, models
import django.db.models.deletion


def set_default_classifier(apps, schema_editor):
    """Установка дефолтного классификатора для существующих записей"""
    InspectorViolation = apps.get_model('inspector', 'InspectorViolation')
    ViolationClassifier = apps.get_model('violations', 'ViolationClassifier')
    
    # Получаем первый доступный классификатор
    first_classifier = ViolationClassifier.objects.filter(is_active=True).first()
    if first_classifier:
        # Обновляем все записи без классификатора
        InspectorViolation.objects.filter(violation_classifier__isnull=True).update(
            violation_classifier=first_classifier
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_inspectorviolation_violation_classifier'),
        ('violations', '0002_violationclassifier_violation_violation_classifier'),
    ]

    operations = [
        # Сначала устанавливаем дефолтные значения для существующих записей
        migrations.RunPython(set_default_classifier),
        
        # Затем изменяем поля
        migrations.AlterField(
            model_name='inspectorviolation',
            name='violation_type',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='violations', 
                to='inspector.violationtype', 
                verbose_name='Тип нарушения'
            ),
        ),
        migrations.AlterField(
            model_name='inspectorviolation',
            name='violation_classifier',
            field=models.ForeignKey(
                help_text='Тип замечания из классификатора производства работ',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='inspector_violations',
                to='violations.violationclassifier',
                verbose_name='Классификатор нарушения'
            ),
        ),
    ]
