# Generated by Django 5.2.6 on 2025-09-29 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0003_auto_20250929_0239'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inspector.inspectorviolation', verbose_name='Нарушение')),
            ],
            options={
                'verbose_name': 'Комментарий к нарушению',
                'verbose_name_plural': 'Комментарии к нарушениям',
                'ordering': ['-created_at'],
            },
        ),
    ]
