# Generated by Django 5.2.6 on 2025-09-30 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0004_violationcomment'),
        ('projects', '0007_add_qr_code_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectorviolation',
            name='qr_code_verified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_violations', to='projects.projectqrcode', verbose_name='QR-код для верификации'),
        ),
        migrations.AddField(
            model_name='inspectorviolation',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('qr_code', 'QR-код'), ('geolocation', 'Геолокация')], max_length=20, null=True, verbose_name='Метод подтверждения местонахождения'),
        ),
    ]
