# Generated by Django 5.2.6 on 2025-09-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(help_text='Название Excel файла', max_length=255, verbose_name='Исходный файл')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_specification', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Электронная спецификация',
                'verbose_name_plural': 'Электронные спецификации',
            },
        ),
        migrations.CreateModel(
            name='NetworkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(help_text='Название Excel файла с графиком', max_length=255, verbose_name='Исходный файл графика')),
                ('project_duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общая продолжительность (дни)')),
                ('critical_path_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность критического пути (дни)')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_schedule', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Сетевой график',
                'verbose_name_plural': 'Сетевые графики',
            },
        ),
        migrations.CreateModel(
            name='SpecificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код работ/материала')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование работ/материала')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Количество')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Общая стоимость')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Категория работ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в спецификации')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.electronicspecification', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'Элемент спецификации',
                'verbose_name_plural': 'Элементы спецификации',
                'ordering': ['specification', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, verbose_name='ID задачи в графике')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование задачи')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Продолжительность (дни)')),
                ('early_start', models.PositiveIntegerField(help_text='День от начала проекта', verbose_name='Раннее начало (день)')),
                ('early_finish', models.PositiveIntegerField(verbose_name='Раннее окончание (день)')),
                ('late_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Позднее начало (день)')),
                ('late_finish', models.PositiveIntegerField(blank=True, null=True, verbose_name='Позднее окончание (день)')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Задача на критическом пути')),
                ('resource_names', models.TextField(blank=True, help_text='Список ресурсов через запятую', verbose_name='Ресурсы')),
                ('predecessors', models.TextField(blank=True, help_text='ID предшествующих задач через запятую', verbose_name='Предшествующие задачи')),
                ('successors', models.TextField(blank=True, help_text='ID последующих задач через запятую', verbose_name='Последующие задачи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в графике')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.networkschedule', verbose_name='График')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.worktype', verbose_name='Тип работ')),
            ],
            options={
                'verbose_name': 'Задача графика',
                'verbose_name_plural': 'Задачи графика',
                'ordering': ['schedule', 'early_start', 'order'],
                'unique_together': {('schedule', 'task_id')},
            },
        ),
    ]
