# Generated by Django 5.2.6 on 2025-09-24 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_electronicspecification_networkschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('notification_type', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('success', 'Успех'), ('task', 'Задача'), ('inspection', 'Проверка'), ('violation', 'Нарушение'), ('project_update', 'Обновление проекта')], default='info', max_length=20, verbose_name='Тип уведомления')),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип связанного объекта')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает активации'), ('foreman_assigned', 'Прораб назначен'), ('checklist_filling', 'Заполнение чек-листа'), ('inspector_review', 'На рассмотрении инспектора'), ('approved', 'Одобрено'), ('activated', 'Активирован'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус активации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foreman_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_completed_at', models.DateTimeField(blank=True, null=True)),
                ('inspector_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('inspector_notes', models.TextField(blank=True, verbose_name='Заметки инспектора')),
                ('activation_document', models.FileField(blank=True, null=True, upload_to='activation_documents/', verbose_name='Документ об активации')),
                ('assigned_foreman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_activations', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный прораб')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_activations', to=settings.AUTH_USER_MODEL, verbose_name='Инициировал активацию')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to='projects.project', verbose_name='Проект')),
                ('reviewing_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_activations', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий инспектор')),
            ],
            options={
                'verbose_name': 'Активация проекта',
                'verbose_name_plural': 'Активации проектов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Создана заявка'), ('foreman_assigned', 'Назначен прораб'), ('checklist_started', 'Начато заполнение чек-листа'), ('checklist_completed', 'Чек-лист заполнен'), ('sent_for_review', 'Отправлено на проверку'), ('inspector_assigned', 'Назначен инспектор'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('activated', 'Проект активирован'), ('comment_added', 'Добавлен комментарий')], max_length=20, verbose_name='Тип события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('activation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.projectactivation', verbose_name='Активация')),
            ],
            options={
                'verbose_name': 'Событие активации',
                'verbose_name_plural': 'События активации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivationChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_at', models.DateTimeField(auto_now_add=True)),
                ('documentation_complete', models.BooleanField(default=False, verbose_name='Документация готова')),
                ('site_prepared', models.BooleanField(default=False, verbose_name='Строительная площадка подготовлена')),
                ('safety_measures', models.BooleanField(default=False, verbose_name='Меры безопасности обеспечены')),
                ('equipment_ready', models.BooleanField(default=False, verbose_name='Оборудование готово')),
                ('permits_obtained', models.BooleanField(default=False, verbose_name='Разрешения получены')),
                ('utilities_connected', models.BooleanField(default=False, verbose_name='Коммуникации подключены')),
                ('access_organized', models.BooleanField(default=False, verbose_name='Доступ к объекту организован')),
                ('documentation_notes', models.TextField(blank=True, verbose_name='Примечания по документации')),
                ('site_notes', models.TextField(blank=True, verbose_name='Примечания по площадке')),
                ('safety_notes', models.TextField(blank=True, verbose_name='Примечания по безопасности')),
                ('equipment_notes', models.TextField(blank=True, verbose_name='Примечания по оборудованию')),
                ('permits_notes', models.TextField(blank=True, verbose_name='Примечания по разрешениям')),
                ('utilities_notes', models.TextField(blank=True, verbose_name='Примечания по коммуникациям')),
                ('access_notes', models.TextField(blank=True, verbose_name='Примечания по доступу')),
                ('overall_readiness', models.BooleanField(default=False, verbose_name='Объект готов к активации')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Дополнительные примечания')),
                ('filled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Заполнил')),
                ('activation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='projects.projectactivation', verbose_name='Активация')),
            ],
            options={
                'verbose_name': 'Чек-лист активации',
                'verbose_name_plural': 'Чек-листы активации',
            },
        ),
    ]
