# Generated by Django 5.2.6 on 2025-09-24 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20250924_1647'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Проект создан'), ('status_changed', 'Изменен статус'), ('foreman_assigned', 'Назначен прораб'), ('foreman_changed', 'Изменен прораб'), ('work_started', 'Начаты работы'), ('work_completed', 'Завершены работы'), ('comment_added', 'Добавлено замечание'), ('violation_added', 'Зарегистрировано нарушение'), ('material_delivered', 'Доставлены материалы'), ('inspection_passed', 'Пройдена проверка'), ('document_uploaded', 'Загружен документ'), ('schedule_changed', 'Изменен график'), ('milestone_reached', 'Достигнута веха'), ('budget_updated', 'Обновлен бюджет'), ('completion_updated', 'Обновлен процент готовности')], max_length=20, verbose_name='Тип события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие проекта',
                'verbose_name_plural': 'События проекта',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='projects_pr_project_b5fce8_idx'), models.Index(fields=['event_type', '-created_at'], name='projects_pr_event_t_5d507f_idx')],
            },
        ),
    ]
