# Generated by Django 5.2.6 on 2025-09-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activationchecklist',
            old_name='documentation_notes',
            new_name='regulatory_documentation_notes',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='access_notes',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='access_organized',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='documentation_complete',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='equipment_notes',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='equipment_ready',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='permits_notes',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='permits_obtained',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='safety_measures',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='safety_notes',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='site_notes',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='site_prepared',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='utilities_connected',
        ),
        migrations.RemoveField(
            model_name='activationchecklist',
            name='utilities_notes',
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='construction_control_order',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие приказа на ответственное лицо, осуществляющее строительный контроль (с указанием идентификационного номера в НРС в области строительства)'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='construction_control_order_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по приказу на ответственного за строительный контроль'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='construction_manager_order',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие приказа на ответственное лицо, осуществляющего строительство (производство работ)'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='construction_manager_order_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по приказу на ответственного за строительство'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='engineering_site_preparation',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Инженерная подготовка строительной площадки'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='engineering_site_preparation_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по инженерной подготовке площадки'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='fire_safety_stands',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие стендов пожарной безопасности с указанием на схеме мест источников воды, средств пожаротушения'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='fire_safety_stands_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по стендам пожарной безопасности'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='general_plan',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие генерального плана (ситуационного плана)'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='general_plan_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по генеральному плану'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='geodetic_breakdown_act',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие акта геодезической разбивочной основы, принятых знаков (реперов)'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='geodetic_breakdown_act_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по геодезической разбивочной основе'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='information_boards',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие информационных щитов (знаков) с указанием: наименование объекта; наименование Застройщика (технического Заказчика); наименование подрядной организации; наименование проектной организации; сроки строительства; контактные телефоны ответственных по приказу лиц по организации'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='information_boards_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по информационным щитам'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='project_documentation_stamp',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие проектной документации со штампом «В производство работ»'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='project_documentation_stamp_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по проектной документации'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='project_supervision_order',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие приказа на ответственное лицо, осуществляющее подготовку проектной документации, авторский надзор'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='project_supervision_order_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по приказу на ответственного за проектную документацию'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='regulatory_documentation',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие разрешительной, организационно-технологической, рабочей документации'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='temporary_infrastructure',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Фактическое размещение временной инженерной и бытовой инфраструктуры площадки (включая стоянку автотранспорта) согласно проекту организации. Соответствие размещённых временных инфраструктуры требованиям электробезопасности, пожарных, санитарно-эпидемиологических норм и правил'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='temporary_infrastructure_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по временной инфраструктуре'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='vehicle_cleaning_points',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие пунктов очистки или мойки колес транспортных средств на выездах со строительной площадки'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='vehicle_cleaning_points_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по пунктам очистки транспорта'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='waste_containers',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие бункеров или контейнеров для сбора отдельно бытового и отдельно строительного мусора'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='waste_containers_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по контейнерам для мусора'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='work_production_project',
            field=models.CharField(blank=True, choices=[('yes', 'ДА'), ('no', 'НЕТ'), ('not_required', 'Не требуется')], max_length=15, null=True, verbose_name='Наличие проекта производства работ (утвержденного руководителем подрядной организации, согласованного Заказчиком, проектировщиком, эксплуатирующей организацией)'),
        ),
        migrations.AddField(
            model_name='activationchecklist',
            name='work_production_project_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по проекту производства работ'),
        ),
    ]
