# Generated by Django 5.2.6 on 2025-09-30 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_documentation_notes_activationchecklist_regulatory_documentation_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, help_text='Код, зашитый в QR-код', unique=True, verbose_name='Уникальный код')),
                ('name', models.CharField(help_text='Описание места размещения QR-кода', max_length=100, verbose_name='Название кода')),
                ('location_description', models.CharField(blank=True, help_text='Описание места, где расположен QR-код', max_length=255, verbose_name='Описание места')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Оставьте пустым для постоянного кода', null=True, verbose_name='Дата истечения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал код')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'QR-код проекта',
                'verbose_name_plural': 'QR-коды проектов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='projects.projectqrcode', verbose_name='QR-код')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Верификация QR-кода',
                'verbose_name_plural': 'Верификации QR-кодов',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projectqrcode',
            index=models.Index(fields=['code'], name='projects_pr_code_379b71_idx'),
        ),
        migrations.AddIndex(
            model_name='projectqrcode',
            index=models.Index(fields=['project', '-created_at'], name='projects_pr_project_b95e38_idx'),
        ),
        migrations.AddIndex(
            model_name='qrverification',
            index=models.Index(fields=['qr_code', '-verified_at'], name='projects_qr_qr_code_c5bb08_idx'),
        ),
        migrations.AddIndex(
            model_name='qrverification',
            index=models.Index(fields=['user', '-verified_at'], name='projects_qr_user_id_07237b_idx'),
        ),
    ]
