# Generated by Django 5.2.6 on 2025-09-30 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_qr_code_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Дата прогноза')),
                ('temperature', models.IntegerField(verbose_name='Температура (°C)')),
                ('weather_main', models.CharField(max_length=50, verbose_name='Основные погодные условия')),
                ('weather_description', models.CharField(max_length=100, verbose_name='Описание погоды')),
                ('wind_speed', models.FloatField(default=0, verbose_name='Скорость ветра (м/с)')),
                ('humidity', models.IntegerField(default=0, verbose_name='Влажность (%)')),
                ('precipitation', models.FloatField(default=0, verbose_name='Осадки (мм)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Прогноз погоды',
                'verbose_name_plural': 'Прогнозы погоды',
                'ordering': ['forecast_date'],
                'unique_together': {('project', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherWorkRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_condition', models.CharField(choices=[('clear', 'Ясно'), ('clouds', 'Облачно'), ('rain', 'Дождь'), ('snow', 'Снег'), ('thunderstorm', 'Гроза'), ('mist', 'Туман'), ('extreme_cold', 'Экстремальный холод'), ('extreme_heat', 'Экстремальная жара'), ('high_wind', 'Сильный ветер')], max_length=20, verbose_name='Погодные условия')),
                ('min_temperature', models.IntegerField(blank=True, null=True, verbose_name='Мин. температура (°C)')),
                ('max_temperature', models.IntegerField(blank=True, null=True, verbose_name='Макс. температура (°C)')),
                ('max_wind_speed', models.IntegerField(blank=True, null=True, verbose_name='Макс. скорость ветра (м/с)')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий риск'), ('medium', 'Средний риск'), ('high', 'Высокий риск'), ('critical', 'Критический риск')], max_length=10, verbose_name='Уровень риска')),
                ('recommendation', models.TextField(verbose_name='Рекомендация')),
                ('is_work_allowed', models.BooleanField(default=True, verbose_name='Работы разрешены')),
                ('delay_hours', models.IntegerField(default=0, verbose_name='Рекомендуемая задержка (часы)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_recommendations', to='projects.worktype', verbose_name='Тип работ')),
            ],
            options={
                'verbose_name': 'Погодная рекомендация для работ',
                'verbose_name_plural': 'Погодные рекомендации для работ',
                'unique_together': {('work_type', 'weather_condition')},
            },
        ),
    ]
