# Generated by Django 5.2.6 on 2025-09-25 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('projects', '0006_rename_documentation_notes_activationchecklist_regulatory_documentation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdocument',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Адрес доставки будет автоматически заполнен из выбранного проекта', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_documents', to='projects.project', verbose_name='Проект (адрес доставки)'),
        ),
    ]
