# Generated by Django 5.2.6 on 2025-09-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_transportdocument_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdelivery',
            name='ttn_image',
            field=models.ImageField(blank=True, null=True, upload_to='ttn_images/', verbose_name='Фото ТТН'),
        ),
    ]
