# Generated by Django 5.2.6 on 2025-09-22 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('construction_control', 'Служба строительного контроля'), ('foreman', 'Прораб'), ('inspector', 'Инспектор контрольного органа'), ('identifier', 'Идентификатор')], max_length=20, verbose_name='Тип пользователя'),
        ),
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
            ],
            options={
                'verbose_name': 'QR-токен',
                'verbose_name_plural': 'QR-токены',
                'ordering': ['-created_at'],
            },
        ),
    ]
