# Generated by Django 5.2.6 on 2025-09-22 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type_qrtoken'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtoken',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект, на котором находится прораб', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения'),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_qr_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Подтвержден контролером'),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Прораб (создатель)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('construction_control', 'Служба строительного контроля'), ('foreman', 'Прораб'), ('inspector', 'Инспектор контрольного органа')], max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
