# Generated by Django 5.2.6 on 2025-09-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_qrtoken_project_qrtoken_verified_at_and_more'),
        ('projects', '0002_electronicspecification_networkschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrtoken',
            name='project',
            field=models.ForeignKey(help_text='Проект, на котором находится прораб', on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект'),
        ),
    ]
