# Generated by Django 5.2.6 on 2025-09-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0006_rename_documentation_notes_activationchecklist_regulatory_documentation_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file_source', models.CharField(blank=True, max_length=255, verbose_name='Источник файла')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_specifications', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Спецификация работ',
                'verbose_name_plural': 'Спецификации работ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSpecificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование работ')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость за единицу')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общая стоимость')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.workspecification', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'Элемент спецификации',
                'verbose_name_plural': 'Элементы спецификации',
                'ordering': ['specification', 'order'],
            },
        ),
    ]
