# Generated by Django 5.2.6 on 2025-09-22 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория нарушения',
                'verbose_name_plural': 'Категории нарушений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание нарушения')),
                ('location', models.CharField(help_text="Координаты в формате 'lat,lng'", max_length=100, verbose_name='Место нарушения')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('resolved', 'Устранено'), ('verified', 'Проверено'), ('rejected', 'Отклонено'), ('overdue', 'Просрочено')], default='open', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критичный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('detected_at', models.DateTimeField(verbose_name='Дата и время обнаружения')),
                ('deadline', models.DateTimeField(verbose_name='Срок устранения')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата устранения')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('photos', models.JSONField(blank=True, null=True, verbose_name='Фотографии')),
                ('documents', models.JSONField(blank=True, null=True, verbose_name='Документы')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('worker_count', models.IntegerField(blank=True, null=True, verbose_name='Количество рабочих')),
                ('equipment_count', models.IntegerField(blank=True, null=True, verbose_name='Количество техники')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_violations', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за устранение')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_violations', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='projects.project', verbose_name='Объект')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_violations', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Нарушение',
                'verbose_name_plural': 'Нарушения',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание мер по устранению')),
                ('photos', models.JSONField(blank=True, null=True, verbose_name='Фотографии устранения')),
                ('documents', models.JSONField(blank=True, null=True, verbose_name='Документы')),
                ('location', models.CharField(blank=True, help_text="Координаты в формате 'lat,lng'", max_length=100, null=True, verbose_name='Место устранения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolved_violations', to=settings.AUTH_USER_MODEL, verbose_name='Кто устранил')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='violations.violation', verbose_name='Нарушение')),
            ],
            options={
                'verbose_name': 'Устранение нарушения',
                'verbose_name_plural': 'Устранения нарушений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код нарушения')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование нарушения')),
                ('type_field', models.CharField(max_length=255, verbose_name='Тип')),
                ('kind', models.CharField(max_length=255, verbose_name='Вид')),
                ('source', models.CharField(choices=[('construction_control', 'Служба строительного контроля'), ('inspector', 'Контрольный орган')], max_length=20, verbose_name='Источник классификатора')),
                ('regulatory_deadline_days', models.IntegerField(verbose_name='Регламентный срок устранения (дни)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violation_types', to='violations.violationcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип нарушения',
                'verbose_name_plural': 'Типы нарушений',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='violations.violationtype', verbose_name='Тип нарушения'),
        ),
    ]
