# Generated by Django 5.2.6 on 2025-09-28 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Основная категория нарушения', max_length=255, verbose_name='Категория')),
                ('kind', models.CharField(help_text='Вид нарушения (Устранимое, Неустранимое и т.д.)', max_length=255, verbose_name='Вид')),
                ('type_name', models.CharField(help_text='Тип нарушения (Грубое, Значительное и т.д.)', max_length=255, verbose_name='Тип')),
                ('name', models.TextField(help_text='Полное наименование нарушения', verbose_name='Наименование')),
                ('regulatory_deadline_days', models.PositiveIntegerField(blank=True, help_text='Количество дней на устранение нарушения', null=True, verbose_name='Регламентный срок устранения (дни)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Классификатор нарушения',
                'verbose_name_plural': 'Классификатор нарушений',
                'ordering': ['category', 'kind', 'type_name'],
                'unique_together': {('category', 'kind', 'type_name', 'name')},
            },
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_classifier',
            field=models.ForeignKey(blank=True, help_text='Классификатор производства работ', null=True, on_delete=django.db.models.deletion.PROTECT, to='violations.violationclassifier', verbose_name='Классификатор нарушения'),
        ),
    ]
